[profile.default]
solc = "0.8.25"
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]

[rpc_endpoints]
avalanche = "${AVALANCHE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
