[profile.default]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
fuji = "${FUJI_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
avalanche = { key = "${ETHERSCAN_API_KEY}", url = "https://api.snowscan.xyz/api" }
fuji = { key = "${SNOWSCAN_API_KEY}", url = "https://api-testnet.snowscan.xyz/api" }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[fuzz]
runs = 2048
max_test_rejects = 262144

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
